name: Build And Run Test on Ubuntu

on:
  workflow_dispatch:

env:
  BUILD_TYPE: Release

jobs:
  Build_and_Run_GTest:
    name: Build and Run GoogleTest
    runs-on: ubuntu-latest

    steps:    
    - uses: actions/checkout@v2
    - uses: ilammy/msvc-dev-cmd@v1
    - name: Build something requiring CL.EXE
      run: |
        cmake -G "NMake Makefiles" .
        nmake
      # ...