name: Build And Run Test on Windows

on:
  push:
    branches: [ main ]
  pull_request: 
  workflow_dispatch:

env:
  BUILD_TYPE: Release

jobs:
  Build_and_Run_GTest:
    name: Build and Run GoogleTest
    runs-on: windows-latest

    steps:
    - uses: actions/checkout@v2
      with:
        submodules: recursive
        
    - name: Install LibTiff
      run: install_win_prereq.bat

    - name: Set environment variable
      run: |
        VER=$(cat VERSION)
        echo "TIFF_INCLUDE_DIR=C:/Program Files (x86)/tiff/include" >> $GITHUB_ENV
        echo "TIFF_LIBRARY_RELEASE=C:/Program Files (x86)/tiff/lib/tiff.lib" >> $GITHUB_ENV
  
    - name: Configure CMake
      run: cmake -B ${{github.workspace}}/build -DCMAKE_BUILD_TYPE=${{env.BUILD_TYPE}} -DBUILD_CLI=ON

    - name: Build
      run: cmake --build ${{github.workspace}}/build --config ${{env.BUILD_TYPE}} --parallel 2

    - name: Run GTest Suite
      working-directory: ${{github.workspace}}/build
      # Execute tests.  
      run: ./tests/runAllTests  -C ${{env.BUILD_TYPE}}
      

  Build_and_Run_UnitTest:
    name: Build and Run Unit Tests
    runs-on: windows-latest

    steps:
    - uses: actions/checkout@v2
      with:
        submodules: recursive
              
    - name: Setup Python
      uses: actions/setup-python@v2
      with:
        python-version: "3.x"

    - name: Install Dependencies
      run: python -m pip install --upgrade wheel numpy pandas

    - name: Install LibTiff
      run: install_win_prereq.bat

    - name: Set environment variable
      run: |
        VER=$(cat VERSION)
        echo "TIFF_INCLUDE_DIR=C:/Program Files (x86)/tiff/include" >> $GITHUB_ENV
        echo "TIFF_LIBRARY_RELEASE=C:/Program Files (x86)/tiff/lib/tiff.lib" >> $GITHUB_ENV

    - name: Install Nyxus
      working-directory: ${{github.workspace}}
      run: python3 setup.py install

    - name: Run Unit Tests
      working-directory: ${{github.workspace}}
      run: python3 -m unittest discover tests/python/