name: Build And Run Test

on:
  push:
    branches: [ main ]
  pull_request: 

env:
  BUILD_TYPE: Release

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
      with:
        submodules: recursive
        
    - name: Install LibTiff
      run: sudo apt install libtiff-dev
      
    # - name: Configure CMake
    #   run: cmake -B ${{github.workspace}}/build -DCMAKE_BUILD_TYPE=${{env.BUILD_TYPE}} -DBUILD_CLI=ON

    # - name: Build
    #   run: cmake --build ${{github.workspace}}/build --config ${{env.BUILD_TYPE}}

    # - name: Run GTest Suite
    #   working-directory: ${{github.workspace}}/build
    #   # Execute tests.  
    #   run: ./tests/runAllTests  -C ${{env.BUILD_TYPE}}
      

    # Setup Python for PyTest
    - name: Setup Python
      uses: actions/setup-python@v2
      with:
        python-version: "3.x"

    - name: Install pipenv
      run: python -m pip install --upgrade pipenv wheel
    - id: cache-pipenv
      uses: actions/cache@v1
      with:
        path: ~/.local/share/virtualenvs
        key: ${{ runner.os }}-pipenv-${{ hashFiles('**/Pipfile.lock') }}

    - name: Install Numpy
      run: pipenv install numpy

    - name: Install Pandas
      run: pipenv install pandas

    - name: Start virual env
      working-directory: ${{github.workspace}}
      run: pipenv shell

    - name: Install Nyxus
      working-directory: ${{github.workspace}}
      run: python3 setup.py install