name: Build And Run Test

on:
  push:
    branches: [ main ]
  pull_request: 

env:
  BUILD_TYPE: Release

jobs:
  Build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
      with:
        submodules: recursive
        
    - name: Install LibTiff
      run: sudo apt install libtiff-dev
      
    # Setup Python for PyTest
    - name: Setup Python
      uses: actions/setup-python@v2
      with:
        python-version: "3.x"

    - name: Install Dependencies
      run: python -m pip install --upgrade wheel numpy pandas

    - name: Install Nyxus
      working-directory: ${{github.workspace}}
      run: python3 setup.py install

    - name: Run GTest
      working-directory: ${{github.workspace}}/build
      run: ./tests/runAllTests