name: Build And Run Test on Windows

on:
  push:
    branches: [ main ]
  pull_request: 
  workflow_dispatch:

env:
  BUILD_TYPE: Release
  TIFF_LIBRARY_RELEASE: ${{ProgramFiles(x86)}}/tiff/lib/tiff.lib
  TIFF_INCLUDE_DIR: ${{ProgramFiles(x86)}}/tiff/include


jobs:
  Build_and_Run_GTest:
    name: Build and Run GoogleTest
    runs-on: windows-latest

    steps:
    - uses: actions/checkout@v2
      with:
        submodules: recursive
        
    - name: Install LibTiff
      working-directory: ${{github.workspace}}
      shell: cmd
      run: install_win_prereq.bat

    - name: Configure CMake
      run: cmake -B ${{github.workspace}}/build -DCMAKE_BUILD_TYPE=${{env.BUILD_TYPE}} -DBUILD_CLI=ON

    - name: Build
      run: cmake --build ${{github.workspace}}/build --config ${{env.BUILD_TYPE}} --parallel 2

    - name: Run GTest Suite
      working-directory: ${{github.workspace}}/build
      # Execute tests.  
      run: ./tests/runAllTests  -C ${{env.BUILD_TYPE}}
      

  Build_and_Run_UnitTest:
    name: Build and Run Unit Tests
    runs-on: windows-latest

    steps:
    - uses: actions/checkout@v2
      with:
        submodules: recursive
              
    - name: Setup Python
      uses: actions/setup-python@v2
      with:
        python-version: "3.x"

    - name: Install Dependencies
      run: python -m pip install --upgrade wheel numpy pandas pytest

    - name: Install LibTiff
      working-directory: ${{github.workspace}}
      shell: cmd
      run: install_win_prereq.bat

    - name: Install Nyxus
      working-directory: ${{github.workspace}}
      run: python3 setup.py install

    - name: Run PyTest
      working-directory: ${{github.workspace}}
      run: python3 -m pytest tests/python/