name: Build And Run Test on Mac

on:
  push:
    branches: [ main ]
  pull_request: 
  workflow_dispatch:

env:
  BUILD_TYPE: Release

jobs:
  Build_and_Run_GTest:
    name: Build and Run GoogleTest
    runs-on: macos-11
    defaults:
      run:
        shell: bash -l {0}

    steps:
    - uses: actions/checkout@v2
      with:
        submodules: recursive
        
    - uses: conda-incubator/setup-miniconda@v2
      with:
        activate-environment: anaconda-client-env
        python-version: 3.7
        channels: conda-forge
        auto-activate-base: false

    - name: Install Conda Dependencies
      run: |
        conda install compilers z5py libtiff boost nlohmann_json blosc pybind11 xtensor xsimd

    - name: Configure CMake
      run: cmake -B ${{github.workspace}} -DCMAKE_BUILD_TYPE=${{env.BUILD_TYPE}} -DBUILD_CLI=ON -DCMAKE_PREFIX_PATH=$CONDA_PREFIX -DCMAKE_INSTALL_PREFIX=$CONDA_PREFIX

    - name: Build
      run: cmake --build ${{github.workspace}} --config ${{env.BUILD_TYPE}} --parallel 2

    - name: Run GTest Suite
      working-directory: ${{github.workspace}}
      # Execute tests.  
      run: ./tests/runAllTests  -C ${{env.BUILD_TYPE}}
      

  Build_and_Run_PyTest:
    name: Build and Run PyTest
    runs-on: macos-11
    defaults:
      run:
        shell: bash -l {0}

    steps:
    - uses: actions/checkout@v2
      with:
        submodules: recursive
        
    - uses: conda-incubator/setup-miniconda@v2
      with:
        activate-environment: anaconda-client-env
        python-version: 3.7
        channels: conda-forge
        auto-activate-base: false

    - name: Install Conda Dependencies
      run: |
        conda install compilers z5py libtiff boost nlohmann_json blosc pybind11 xtensor xsimd wheel numpy pandas pytest requests

    - name: Install Nyxus
      working-directory: ${{github.workspace}}
      run: CMAKE_ARGS="-DCMAKE_PREFIX_PATH=$CONDA_PREFIX -DCMAKE_INSTALL_PREFIX=$CONDA_PREFIX" python setup.py install

    - name: Run PyTest
      working-directory: ${{github.workspace}}
      run: python -m pytest tests/python/