name: Publish to PyPi

if: github.event_name == 'release' && github.event.action == 'created'

env:
  BUILD_TYPE: Release

jobs:
  Publish:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
      with:
        submodules: recursive      

    - name: Create ManyLinux Docker
      run: docker build . -f .github/LinuxWheelBuilder  -t linuxbuilder

    - name: Build ManyLinux Wheels 
      run: docker run -v $(pwd):/io  linuxbuilder:latest
    
    - name: Install Dependencies
      run: python -m pip install --upgrade twine requests

    - name: Publish to PyPi
      run: python -m twine upload dist/*
      env:
        TWINE_USERNAME: __token__
        TWINE_PASSWORD: ${{ secrets.TWINE_API_KEY }}
        TWINE_REPOSITORY: testpypi