name: Publish Docker image
on:
  release:
    types: [published]
  workflow_dispatch:
  
env:
  BUILD_TYPE: Release

jobs:
  push_to_registry:
    name: Push Docker image to Docker Hub
    runs-on: ubuntu-20.04
    defaults:
      run:
        shell: bash -l {0}

    steps:
    - uses: actions/checkout@v3

    - uses: conda-incubator/setup-miniconda@v2
      with:
        activate-environment: anaconda-client-env
        python-version: 3.8
        channels: conda-forge
        auto-activate-base: false

    - name: Install Conda Dependencies
      run: |
        conda install compilers=1.1.1  --file ${{github.workspace}}/ci-utils/envs/conda_cpp.txt --file ${{github.workspace}}/ci-utils/envs/conda_gpu.txt

    - name: Configure CMake
      run: cmake -B ${{github.workspace}} -DCMAKE_BUILD_TYPE=${{env.BUILD_TYPE}} -DBUILD_CLI=ON -DUSE_GPU=ON -DUSEARROW=ON -DCMAKE_PREFIX_PATH=$CONDA_PREFIX -DCMAKE_INSTALL_PREFIX=$CONDA_PREFIX

    - name: Build
      run: cmake --build ${{github.workspace}} --config ${{env.BUILD_TYPE}} --parallel 2
      
    - name: Copy 3rd-party libraries to staging directory
      working-directory: ${{github.workspace}}
      run: |
        bash ci-utils/docker_copy_3rd_party_libs.sh $CONDA_PREFIX

    - name: Create Version File
      run: python setup.py --version| grep -v init > VERSION
    
    - name: Set variable
      run: |
        VER=$(cat VERSION)
        echo "VERSION=$VER" >> $GITHUB_ENV

    - name: Log in to Docker Hub
      uses: docker/login-action@f054a8b539a109f9f41c372932f1ae047eff08c9
      with:
        username: ${{ secrets.DOCKER_USERNAME }}
        password: ${{ secrets.DOCKER_TOKEN }}
    
    - name: Extract metadata (tags, labels) for Docker
      id: meta
      uses: docker/metadata-action@98669ae865ea3cffbcbaa878cf57c20bbf1c6c38
      with:
        images: polusai/nyxus
    
    - name: Build and push Docker image
      env:
        DOCKER_REPO: nyxus
      uses: docker/build-push-action@ad44023a93711e3deb337508980b4b5e9bcdc5dc
      with:
        context: .
        push: true
        tags: polusai/${{ env.DOCKER_REPO }}:${{ env.VERSION }}, polusai/${{ env.DOCKER_REPO }}:latest
        labels: ${{ steps.meta.outputs.labels }}
