name: Publish Docker image

on:
  push:
  pull_request: 

env:
  BUILD_TYPE: Release

jobs:
  push_to_registry:
    name: Push Docker image to Docker Hub
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
      with:
        submodules: recursive
        
    - name: Install LibTiff
      run: sudo apt install libtiff-dev
      
    - name: Configure CMake
      run: cmake -B ${{github.workspace}}/build-4-linux -DCMAKE_BUILD_TYPE=${{env.BUILD_TYPE}} -DBUILD_CLI=ON

    - name: Build
      run: cmake --build ${{github.workspace}}//build-4-linux --config ${{env.BUILD_TYPE}} --parallel 2

    - name: Create Version File
      run: python setup.py --version| grep -v init > VERSION
      
    - name: Log in to Docker Hub
      uses: docker/login-action@f054a8b539a109f9f41c372932f1ae047eff08c9
      with:
        username: ${{ secrets.DOCKER_USERNAME }}
        password: ${{ secrets.DOCKER_PASSWORD }}
    
    - name: Extract metadata (tags, labels) for Docker
      id: meta
      uses: docker/metadata-action@98669ae865ea3cffbcbaa878cf57c20bbf1c6c38
      with:
        images: sameeul/testrepo
    
    - name: Build and push Docker image
      uses: docker/build-push-action@ad44023a93711e3deb337508980b4b5e9bcdc5dc
      with:
        context: .
        push: true
        tags: ${{ steps.meta.outputs.tags }}
        labels: ${{ steps.meta.outputs.labels }}